import type {
  PendingDistributionDto,
  PendingResponse,
  ResponsiblesResponse,
} from "./types";

function ago(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

export const MOCK_DISTRIBUTION_RESPONSIBLES: ResponsiblesResponse = {
  responsibles: [
    {
      userId: "u-mock-1",
      name: "Ana Souza",
      email: "ana@eduit.com.br",
      role: "MANAGER",
      participates: true,
      queueLimit: 8,
      volume: 3,
      type: "inbound",
      paused: false,
      lastExecutionAt: ago(12),
      status: "ONLINE",
      hasSchedule: true,
      queueCount: 3,
      eligible: true,
      blockedReasons: [],
    },
    {
      userId: "u-mock-2",
      name: "Bruno Lima",
      email: "bruno@eduit.com.br",
      role: "AGENT",
      participates: true,
      queueLimit: 6,
      volume: 5,
      type: "vendas",
      paused: false,
      lastExecutionAt: ago(45),
      status: "ONLINE",
      hasSchedule: true,
      queueCount: 5,
      eligible: true,
      blockedReasons: [],
    },
    {
      userId: "u-mock-3",
      name: "Carla Mendes",
      email: "carla@eduit.com.br",
      role: "AGENT",
      participates: true,
      queueLimit: 5,
      volume: 5,
      type: "vendas",
      paused: true,
      lastExecutionAt: ago(180),
      status: "AWAY",
      hasSchedule: true,
      queueCount: 2,
      eligible: false,
      blockedReasons: ["ON_PAUSE"],
    },
    {
      userId: "u-mock-4",
      name: "Diego Rocha",
      email: "diego@eduit.com.br",
      role: "AGENT",
      participates: true,
      queueLimit: 4,
      volume: 4,
      type: "suporte",
      paused: false,
      lastExecutionAt: ago(300),
      status: "OFFLINE",
      hasSchedule: false,
      queueCount: 0,
      eligible: false,
      blockedReasons: ["OFFLINE"],
    },
    {
      userId: "u-mock-5",
      name: "Eduarda Nunes",
      email: "eduarda@eduit.com.br",
      role: "AGENT",
      participates: false,
      queueLimit: 0,
      volume: 0,
      type: null,
      paused: false,
      lastExecutionAt: null,
      status: "OFFLINE",
      hasSchedule: true,
      queueCount: 0,
      eligible: false,
      blockedReasons: ["INACTIVE"],
    },
  ],
};

export const MOCK_DISTRIBUTION_PENDING: PendingResponse = {
  pending: [
    {
      id: "mock-pend-1",
      dealId: "mock-deal-10",
      contactId: "mock-ct-10",
      label: "Lead site — Lumina Energia",
      distributionType: "inbound",
      triggerSource: "WEB_FORM",
      attempts: 2,
      lastAttemptAt: ago(18),
      createdAt: ago(42),
    },
    {
      id: "mock-pend-2",
      dealId: null,
      contactId: "mock-ct-11",
      label: "WhatsApp — interesse plano Pro",
      distributionType: "whatsapp",
      triggerSource: "CONVERSATION",
      attempts: 1,
      lastAttemptAt: ago(8),
      createdAt: ago(15),
    },
  ],
};
